how to create analytics plugin
applicaster/developer.applicaster.com pull request #207
Opened 2016-12-04 10:47 UTC by EladBenDavid

This doc describe how to create/edit analytic plugin on separate repository.

2016-12-04 11:09 UTC, meravzanany approved these changes

2016-12-05 12:42 UTC, artanisz requested changes

2016-12-12 10:10 UTC, artanisz requested changes
Please address all the issues related to process and language.

2016-12-13 10:48 UTC, artanisz approved these changes
A great improvement! Thanks for the changes!

2016-12-13 10:49 UTC, merged